select * from pizza_sales

SELECT CAST(CAST(SUM(QUANTITY) AS DECIMAL(10,2)) / 
CAST(COUNT(DISTINCT ORDER_ID) AS DECIMAL(10,2)) AS DECIMAL(10,2)) AS AVG_PIZZAS_PER_ORDER FROM pizza_sales 
SELECT COUNT(DISTINCT ORDER_ID)AS TOTAL_ORDERS FROM pizza_sales

SELECT DATENAME(DW, ORDER_DATE) AS ORDER_DAY,COUNT(DISTINCT ORDER_ID)AS TOTAL_ORDERS FROM pizza_sales
GROUP BY DATENAME(DW,ORDER_DATE)

SELECT DATENAME(MONTH, ORDER_DATE) AS ORDER_MONTH,COUNT(DISTINCT ORDER_ID)AS TOTAL_ORDERS FROM pizza_sales
GROUP BY DATENAME(MONTH,ORDER_DATE)
ORDER BY TOTAL_ORDERS DESC

SELECT PIZZA_CATEGORY,
SUM(TOTAL_PRICE) AS TOTAL_SALES,
SUM(TOTAL_PRICE)*100/(SELECT SUM(TOTAL_PRICE)FROM pizza_sales) AS PCT
FROM pizza_sales
GROUP BY PIZZA_CATEGORY

SELECT PIZZA_SIZE,
CAST(SUM(TOTAL_PRICE) AS DECIMAL(10,2)) AS TOTAL_SALES,
CAST(SUM(TOTAL_PRICE)*100/(SELECT SUM(TOTAL_PRICE) FROM pizza_sales WHERE DATEPART(QUARTER,ORDER_DATE)=1) AS DECIMAL(10,2)) AS PCT
FROM pizza_sales
WHERE DATEPART(QUARTER,ORDER_DATE) = 1
GROUP BY PIZZA_SIZE
ORDER BY PCT DESC

select TOP 5 pizza_name,sum(total_price) as total_REVENUE FROM pizza_sales
GROUP BY pizza_name
ORDER BY TOTAL_REVENUE DESC

select TOP 5 pizza_name,sum(QUANTITY) as total_QUANTITY FROM pizza_sales
GROUP BY pizza_name
ORDER BY TOTAL_QUANTITY DESC

select TOP 5 pizza_name,COUNT(DISTINCT ORDER_ID) as total_ORDERS FROM pizza_sales
GROUP BY pizza_name
ORDER BY TOTAL_ORDERS DESC


